[tool.poetry]
name = "statsservice"
version = "0.1.4"
description = "Stats Service for MONARC."
authors = ["CÃ©dric Bonhomme <cedric@cedricbonhomme.org>"]
license = "AGPL-3.0-or-later"

readme = "README.md"

homepage = "https://github.com/monarc-project/stats-service"
repository = "https://github.com/monarc-project/stats-service"
documentation = "https://monarc-stats-service.readthedocs.io"

keywords = ["monarc", "security", "stats", "flask", "api"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Topic :: Security",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)"
]

include = [
    "README.md",
    "COPYING",
    "runserver.py",
    "instance/production.py.cfg"
]

[tool.poetry.scripts]
monarc-stats-service = "runserver:run"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^1.1.2"
requests = "^2.23.0"
pandas = "^1.0.4"
flask_restx = "^0.2.0"
jsonschema = "^3.2.0"
Flask-SQLAlchemy = "^2.4.3"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]
sphinx = "^3.0.3"
flake8 = "^3.7.9"
sphinx_rtd_theme = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
